config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root "questions#index"
  resources :questions
  resources :answers, only: [:show, :create, :destroy, :update]

  resources :questions do
    resources :answers, only: [:show, :create, :destroy, :update]
  end
end

app/models/answer.rb
class Answer < ActiveRecord::Base
  belongs_to :question 
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/question.rb
class Question < ActiveRecord::Base
  validates :title, null: false, length: {minimum: 1}
  validates :comment, null: false, length: {maximum: 200, minimum: 1}

  has_many :answer, dependent: :destroy  
end

app/controllers/answers_controller.rb
class AnswersController < ApplicationController

  def show
    @answer = Answer.find(params[:id])
  end

  def create
    @question = Question.find(params[:question_id])
    @answer = Answer.new(answer_params)
    @answer.question = @question
    respond_to do |f|
      if @answer.save
        f.html {redirect_to question_path(@question)}
      else
        f.html {redirect_to question_path(@question)}
      end
    end
  end

  def edit
    @answer = Answer.find(params[:id])
  end

  def update

    @answer = Answer.find(params[:id])
    if @answer.update(answer_params)
      redirect_to question_path(@answer.question_id)
    end
  end

  def destroy
    answer = Answer.find(params[:id])
    answer.destroy
    redirect_to question_path(answer.question_id)
  end

  private

  def answer_params
    params.require(:answer).permit(:title, :discription, :question_id, :best_answer)
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/questions_controller.rb
class QuestionsController < ApplicationController
  before_action :set_event, only: [:show, :edit, :update, :destroy]

  def index
    questions = Question.all
    @questions = questions.reverse()

  end

  def show
    @question = Question.find(params[:id])
    @answer = Answer.new
    @time = @question.created_at.strftime("%B %d %Y")
    @answers = @question.answer
    best_answer = @answers.where(best_answer: true)

    if !best_answer.empty?
      index = @answers.find_index {|obj| obj.id == best_answer[0].id}
      @best_answer = @answers.slice(index)
    end
  end

  def new
    @question = Question.new
  end

  def create
    @question = Question.new(question_params)
    respond_to do |f|
      if @question.save
        f.html {redirect_to @question, notice: "Question was saved!"}
      else
        f.html {render action: 'new', notice: "Question not save!"}
      end
    end
  end

  def edit
    @question = Question.find(params[:id])
  end

  def update
    respond_to do |f|
      if @question.update(question_params)
        f.html {redirect_to @question, notince: "Question was Updated"}
      else
        f.html {render action: 'edit'}
      end
    end
  end

  def destroy
    @question.destroy
    respond_to do |f|
      f.html { redirect_to questions_path, notince: "Quetion is deleted!"}
    end
  end



  private

  def set_event
    @question = Question.find(params[:id])
  end

  def question_params
    params.require(:question).permit(:title, :comment)
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RescueMissions</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all' %>
    <%= javascript_include_tag 'application' %>
  </head>

  <body>
    <%=link_to 'Home', questions_path%>

    <%= yield %>


    <div>
      <p class="notice"><%= notice %></p>
      <p class="alert"><%=alert%></p>
    </div>

  </body>


</html>

app/views/questions/_form.html.erb
<%= form_for(@question) do |f|%>
  <%if @question.errors.any?%>
    <div id="error_explanation">
      <h2><%= pluralize(@question.errors.count, "error")%> prohibited this enent form being saved:</h2>
      <ul>
      <% @question.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <%end%>

  <div class="field">
    <%=f.label :title%>
    <%=f.text_field :title%>
  </div>

  <div class="field">
    <%=f.label :comment%>
    <%=f.text_area :comment, size: "24X60"%>
  </div>

  <div class="actions">
    <%=f.submit%>
  </div>

<% end %>

app/views/questions/edit.html.erb
<%=render 'form'%>

app/views/questions/index.html.erb
<h1>Quesions Index</h1>


<% @questions.each do |question| %>
<%=link_to question.title, question_path(question.id)%><br>
<p>Created in <%=question.created_at.strftime("%B %d %Y")%> at</p>
<% end %>



<%=link_to 'New Question', new_question_path%>

app/views/questions/new.html.erb
<h1>New question</h1>

<%= render 'form' %>
<%=link_to 'Back', root_path%>

app/views/questions/show.html.erb
<!-- Question show page  -->

<h1>Question</h1>

<p><%= @question.title %></p>

<p><%=@question.comment%></p>

<p>Created at <%=@time%></p>

<%=link_to 'Delete',@question, method: :delete, data: { confirm: "Are you sure?"}%>
<%=link_to 'Edit', edit_question_path(@question.id)%>


<!--For for add anwsers to the question -->
<%= form_for [@question, @answer], html: {class: ''} do |f| %>
  <%= f.label :title %>
  <%= f.text_field :title %>

  <%= f.label :discription, 'Comment' %>
  <%= f.text_area :discription, size: "60x6" %>

  <%= f.submit "Submit", class: 'button submit-button' %>
<% end %>

<br>

<!-- If is not a best_answer from controller question it will triger thid if -->
<%if @best_answer == nil%>
  <!--Print all answer -->
  <%@answers.each do |answer|%>
    <br><%= answer.title%><br>
    <%= answer.discription%><br>
    <!--Add a button for change the best_answer to true  -->
    <%= form_for answer, :method => :PUT do |f| %>
      <%= f.hidden_field :title, value: answer.title%>
      <%= f.hidden_field :discription, value: answer.discription%>
      <%= f.hidden_field :best_answer, value: true%>

      <%= f.submit "best answer?", class: 'button submit-button' %>
    <% end %>

    <%=link_to 'Delete', answer, method: :delete%>
  <%end%>

<%else%>
<!--if is a best_answer here will be printed -->
  <h1 style="color: blue"><%=@best_answer.title%><br></h1>
  <p style="color: brown"><%=@best_answer.discription%></p>

  <%= form_for @best_answer, :method => :PUT do |f| %>
    <%= f.hidden_field :title, value: @best_answer.title%>
    <%= f.hidden_field :discription, value: @best_answer.discription%>
    <%= f.hidden_field :best_answer, value: false%>

  <%= f.submit "Remove Best Tag", class: 'button submit-button' %>

  <%@answers.each do |answer|%>
    <%if answer.best_answer != true%>
      <br><%= answer.title%><br>
      <%= answer.discription%><br>

      <%=link_to 'Delete', answer, method: :delete%>
    <%end%>
  <%end%>

<% end %>
<%end%>